### ISSUE TITLE
Consume value if present

### ISSUE THREAD

**Issue by tstavinoha** [AlexGalays/option.ts#1]
Hello,

Java's Optional, which is very similar to this library, has a method called ifPresent, which performs an operation on the enclosed value if it is not null (or None)

It is useful for scenarios like this one:

`if (optionalValue != null) {
      doSomething(optionalValue);
}`

becomes:

`Optional.ofNullable(optionalValue).ifPresent(value -> doSomething(optionalValue));`

It returns void, so it is a terminal operation.
Of course, this is much more useful when combined with map, filter, etc.

What are your thoughts on this, and do you think there is a chance to include functionality like this one in this library?

**Comment by AlexGalays** [comment]
Hello,

I agree the general functionality of "running a side effect if the option value is present" is useful.

You can already do it with the following code:

```ts
const myOption = Option(33)

myOption.isDefined() && doSomething(myOption())
```

since isDefined returns an `this is Some` and not just a boolean.

What do you think? Is it expressive enough?

**Comment by tstavinoha** [comment]
Speaking as someone very used to ifPresent functionality, your usage proposal does seem less expressive.

You have to declare an optional variable and manually check whether the value is defined - it kind of a beats the purpose of having an optional monad because it doesn't differ a lot from standard *if* mechanism (for short cases, at least).

Plus, the execution using the *&&* looks a little hacky to me.

ifPresent is great for cases where you don't need to extract the value of the monad and just want to optionally perform an operation based on presence of the value. I have cases like that all the time.

So stuff like this:
```    
let myOption = Option(someObject)
                  .map(o => o.nested1)
                  .flatMap(n1 => n1.optional)
                  .filter(opt => opt.satisfiesCondition());
myOption.isDefined() && initializeOpt(myOption());
```

Would become
```    
Option(someObject)
    .map(o => o.nested1)
    .flatMap(n1 => n1.optional)
    .filter(opt => opt.satisfiesCondition())
    .ifPresent(opt => initialize(opt))
```

Which is a lot cleaner IMHO.

**Comment by AlexGalays** [comment]
That said, `map` would work as well, but maybe it's a bit harder to understand for someone reading the code later than it's being used to run a side effect only.

**Comment by dohzya** [comment]
For what I understand, this function should be called `forEach`, this way its behavior would be understood by anyone without problem (since it match stdlib’s)

**Comment by AlexGalays** [comment]
Since `option.ts` loosely follows scala's naming and `isDefined` could be hard to differantiate from `ifDefined` at a glance, version `0.2.1` now add `forEach`
